// Only mock for parts
import { Part } from '../interfaces/Part';
import { v4 as uuidv4 } from 'uuid';

const mockPartA: Part = {
	id: uuidv4(),
	name: 'Part A',
	features: [
		{
			id: uuidv4(),
			name: 'Feature 1',
			controls: [
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
				{
					id: uuidv4(),
					name: 'Diameter',
					deviation: 0,
					deviationOutTotal: 0,
					status: 'GOOD',
				},
			],
			status: 'WARNING',
		},
	],
};

export {
	mockPartA
};
